apiVersion: v1
kind: Pod
metadata:
  name: hello-wasm
spec:
  nodeSelector:
    kubernetes.io/arch: wasm32-wasi
  containers:
  - name: hello-wasm
    image: ghcr.io/nao-ri/hello-wasm:4.0
    imagePullPolicy: Always
  imagePullSecrets:
    - name: dockerconfigjson-github-com
  tolerations:
  - effect: NoExecute
    key: kubernetes.io/arch
    operator: Equal
    value: wasm32-wasi
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: wasm32-wasi
