apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fibonacci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wasm

  template:
    metadata:
      labels:
        app: wasm
    spec:
      nodeSelector:
        kubernetes.io/arch: wasm32-wasi
      containers:
      - name: fibonacci-wasm
        image: ghcr.io/nao-ri/fibonacci-wasm:1.0
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      tolerations:
      - effect: NoExecute
        key: kubernetes.io/arch
        operator: Equal
        value: wasm32-wasi
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: wasm32-wasi
